name: Code Style
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Verifying code style
    steps:
      - uses: actions/checkout@v6

      - name: Composer Install
        uses: php-actions/composer@v6

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.3
          standard: .phpcs.xml